Help = ("---"
        "\n\n[*] HOST USAGE EXAMPLES"
        "\n\n[*] BASE64 ENCODING - LEVEL 1   "
        "\n$Chatroom"
        "\nvirtualprivacy.py --server chat --port 1337 --host "
        "localhost"
        "\nvirtualprivacy.py -c chat -p 1337 -ip localhost"
        "\nc2"
        "\nvirtualprivacy.py -s c2 -p 1337 -ip 0.0.0.0"
        "\nvirtualprivacy.py --client c2 --port 1337 --host "
        "192.168.2.15"
        "\n$File Transfer"
        "\nvirtualprivacy.py -s ftp -p 1337 -ip 127.0.0.1 --file-in "
        "./helloworld.txt"
        "\nvirtualprivacy.py -c ftp -p 1337 -ip localhost --file-out "
        "./helloworld.txt"
        "\n\n---"
        "\n\n[*] SSL ENCRYPTION - LEVEL 2"
        "\nchat"
        "\nvirtualprivacy.py --server chat -p 1337 -ip localhost "
        "--private-key ./keys/local/jedi_private.pem --certificate "
        "./keys/local/jedi_certificate.pem --only-ssl"
        "\nvirtualprivacy.py --client chat -p 1337 -ip localhost "
        "-crt ./keys/remote/jedi_certificate.crt"
        "\nc2"
        "\nvirtualprivacy.py -s c2 -p 1337 -ip 0.0.0.0 -pr "
        "./keys/local/jedi_private.pem -crt "
        "./keys/local/jedi_certificate.crt --only-ssl"
        "\nvirtualprivacy.py --client c2 --port 1337 --host "
        "192.168.2.15 --certificate ./keys/remote/jedi_certificate.crt"
        "\nftp"
        "\nvirtualprivacy.py --server ftp -p 1337 -ip 0.0.0.0 "
        "-pr ./keys/local/jedi_private.pem -crt "
        "./keys/local/jedi_certificate.crt -os"
        "\nvirtualprivacy.py --client ftp --port 1337 --host "
        "192.168.2.15 -crt ./keys/remote/jedi_private.crt"
        "\n\n---"
        "\n\n[*] VPP ENCRYPTION - LEVEL 3"
        "\nchat"
        "\nvirtualprivacy.py -s chat --port 1337 --host 0.0.0.0 "
        "--private-key ./keys/local/jedi_private.pem"
        "\nvirtualprivacy.py -c chat -p 1337 -ip 192.168.2.15 "
        "-pr ./keys/local/bobcat_public.pem --public "
        "./keys/remote/jedi_public.pem"
        "\nc2"
        "\nvirtualprivacy.py --server c2 -p 1337 -ip 0.0.0.0 "
        "-pr ./keys/local/jedi_private.pem"
        "\nvirtualprivacy.py -c c2 -p 1337 -ip 192.168.2.15 "
        "-pr ./keys/local/bobcat_private.pem -pu "
        "./keys/remote/jedi_public.pem"
        "\nftp"
        "\nvirtualprivacy.py -s ftp -p 1337 -ip 0.0.0.0 "
        "-pr ./keys/local/jedi_private.pem -fi ./thisworks.txt"
        "\nvirtualprivacy.py -c ftp -p 1337 -ip 192.168.2.15 "
        "-pr ./keys/local/bobcat_private.pem -pu "
        "./keys/local/jedi_public.pem -fo ./yesitdoes.txt"
        "\n\n---"
        "\n\n[*] VPP & SSL ENCRYPTION - LEVEL 4"
        "\nchat"
        "\nvirtualprivacy.py -s chat -p 1337 -ip localhost "
        "-pr ./keys/local/jedi_private.pem -crt "
        "./keys/local/jedi_certificate.pem"
        "\nvirtualprivacy.py -c chat -p 1337 -ip localhost "
        "-crt ./keys/remote/jedi_certificate.crt -pr "
        "./keys/local/bobcat_private.pem -pu "
        "./keys/local/jedi_public.pem"
        "\nc2"
        "\nvirtualprivacy.py -s c2 -p 1337 -ip 0.0.0.0 -pr "
        "./keys/local/jedi_private.pem -crt "
        "./keys/local/jedi_certificate.crt"
        "\nvirtualprivacy.py -c c2 -p 1337 -ip 192.168.2.15 "
        "-crt ./keys/remote/jedi_certificate.crt"
        " -pr ./keys/local/bobcat_private.pem -pu "
        "./keys/local/jedi_public.pem"
        "\nftp"
        "\nvirtualprivacy.py --server ftp -p 1337 -ip 0.0.0.0 "
        "-pr ./keys/local/jedi_private.pem -crt "
        "./keys/local/jedi_certificate.crt"
        "\nvirtualprivacy.py --client ftp -p 1337 -ip "
        "192.168.2.15 -crt ./keys/remote/jedi_private.crt -pr "
        "./keys/local/bobcat_private.pem -pu "
        "./keys/local/jedi_public.pem")

with open('helpstring.txt', 'w') as f:
    f.write(Help)
